name: Close Done Issues

on:
  workflow_dispatch: # Permite ejecutar el workflow manualmente
  issues:
    types:
      - edited

jobs:
  close_done_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the issue is marked as Done
        if: github.event.changes.project_card
        run: |
          if [[ "${{ github.event.issue.state }}" != "closed" ]]; then
            issue_state=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }})
            
            project_column=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/projects/columns/${{ github.event.project_card.column_id }})

            if [[ "$project_column" == *"Done"* ]]; then
              curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -d '{"state": "closed"}' \
                https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
            fi
          fi
